# Generated by Django 2.0.6 on 2019-03-20 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mailstops_master',
            fields=[
                ('mailstop', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ms_name', models.CharField(max_length=30)),
                ('ms_route', models.CharField(choices=[('W', 'W'), ('C', 'C'), ('E', 'E')], max_length=1)),
                ('ms_route_order', models.CharField(max_length=3)),
                ('ms_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='packages_master',
            fields=[
                ('pkg_tracking', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('mailstop', models.CharField(max_length=20)),
                ('pkg_status', models.CharField(max_length=20)),
                ('pkg_sign', models.CharField(max_length=20)),
                ('pkg_email', models.CharField(max_length=20)),
                ('pkg_weight', models.CharField(max_length=7)),
                ('pkg_date_rec', models.DateField(default=datetime.date.today)),
                ('pkg_date_del', models.DateField(default=datetime.date.today)),
                ('pkg_remarks', models.CharField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='people_master',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ppl_email', models.CharField(max_length=40)),
                ('ppl_status', models.CharField(choices=[('Available', 'Available'), ('Away', 'Away')], default='Available', max_length=9)),
                ('mailstop', models.CharField(max_length=20)),
            ],
        ),
    ]
