# Generated by Django 2.0.10 on 2019-05-05 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mailstops_master',
            fields=[
                ('mailstop', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('ms_name', models.CharField(default='', max_length=50)),
                ('ms_route', models.CharField(choices=[('W', 'W'), ('C', 'C'), ('E', 'E')], default='W', max_length=10)),
                ('ms_route_order', models.CharField(default='', max_length=3)),
                ('ms_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='packages_master',
            fields=[
                ('pkg_tracking', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('mailstop', models.CharField(default='', max_length=50)),
                ('pkg_status', models.CharField(choices=[('recieved', 'recieved'), ('delivered', 'delivered')], default='', max_length=9)),
                ('pkg_sign', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=10)),
                ('pkg_email', models.CharField(default='', max_length=100)),
                ('pkg_weight', models.CharField(choices=[('s', '1 to 5'), ('m', '6 to 15'), ('l', 'over 16')], max_length=7)),
                ('pkg_date_rec', models.DateField(default=datetime.date.today)),
                ('pkg_date_del', models.DateField(default=datetime.date.today)),
                ('pkg_remarks', models.CharField(default='', max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='people_master',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('ppl_email', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('ppl_status', models.CharField(choices=[('Available', 'Available'), ('Away', 'Away')], default='Available', max_length=9)),
                ('mailstop', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
