# Generated by Django 2.0.6 on 2019-03-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailstops_master',
            name='mailstop',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mailstops_master',
            name='ms_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mailstops_master',
            name='ms_route',
            field=models.CharField(choices=[('W', 'W'), ('C', 'C'), ('E', 'E')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='mailstops_master',
            name='ms_route_order',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='packages_master',
            name='mailstop',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='packages_master',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='packages_master',
            name='pkg_email',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='y', max_length=1),
        ),
        migrations.AlterField(
            model_name='packages_master',
            name='pkg_remarks',
            field=models.CharField(default='', max_length=144),
        ),
        migrations.AlterField(
            model_name='packages_master',
            name='pkg_sign',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='packages_master',
            name='pkg_status',
            field=models.CharField(choices=[('recieved', 'recieved'), ('delivered', 'delivered')], default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='packages_master',
            name='pkg_tracking',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='packages_master',
            name='pkg_weight',
            field=models.CharField(choices=[('s', '1 to 5'), ('m', '6 to 15'), ('l', 'over 16')], max_length=7),
        ),
        migrations.AlterField(
            model_name='people_master',
            name='mailstop',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='people_master',
            name='name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='people_master',
            name='ppl_email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
