# Generated by Django 2.0.6 on 2019-04-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20190319_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages_master',
            name='pkg_email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
